image:
  file: .gitpod.dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: cd frontend-gestion-de-stock 
    init: npm install
    command: npm start
  - before: cd gestiondestock 
    init: mvn clean install
    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview


