spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&userUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: fr.esic.gestiondestock.interceptor.Interceptor
  ## Hibernate DDL Auto(create, create-drop, update)
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081

flickr:
  apiKey: d2b70fac516c6b14589b5944a1b6acbf
  apiSecret: 2945882046a53d67
  appKey: 72157720815129015-ebb718a4522d7b1d
  appSecret: de2e1cd81745f6c4